# Generated by Django 3.1.7 on 2023-09-22 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='confirm_password',
        ),
    ]
